services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb
      # app.prop : Db = SDPDB-35
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    container_name: 2300030402-exam-backend
    build:
    
      context: ./backend-springbootapp
      dockerfile: ../DockerFullstack/backend.Dockerfile
    image: 2300030402-exam-backend
    ports:
      - "8887:7888" # edo okati testing 
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: 2300030402-exam-frontend
    build:
      context: ./frontend-reactapp
      dockerfile: ../DockerFullstack/frontend.Dockerfile
    image: 2300030402-exam-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: